site_name: Poetry Plugin 'Check-Yanked'

repo_url: https://github.com/seapagan/poetry-plugin-check-yanked
repo_name: poetry-plugin-check-yanked

theme:
  name: material
  palette:
    primary: light-blue
    accent: blue
  features:
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seapagan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gnramsay-dev

copyright: © 2024 Grant Ramsay (Seapagan)

# default plugins here are to minify the html, css and js plus enable the search
# plugin. Adjust to your liking.
plugins:
  - search
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true

# edit these MARKDOWN extensions to your liking
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Usage: usage.md
  - GitHub Action: github-action.md
  - To Do: todo.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md
