name: Check for Yanked Packages

on: [push, pull_request]

jobs:
  check-yanked:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run poetry check-yanked
        uses: seapagan/poetry-plugin-check-yanked@add-github-action
        with:
          path: "./"
